packages:
  - "packages/*"
  - "website"
overrides:
  react: ^19.2.7
  react-dom: ^19.2.7
  react-is: ^19.2.7
  typescript: ^6.0.3
  safer-buffer: npm:@nolyfill/safer-buffer@^1
engineStrict: true
allowBuilds:
  lefthook: true
minimumReleaseAge: 600
minimumReleaseAgeExclude:
  - "@resolid/dev"
  - "@resolid/config"
  - "@resolid/utils"
